// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Tue Dec  5 15:21:29 2023

Mux Mux_inst
(
	.keypad_input(keypad_input_sig) ,	// input [7:0] keypad_input_sig
	.IUAU(IUAU_sig) ,	// input  IUAU_sig
	.result(result_sig) ,	// input [7:0] result_sig
	.OUnum(OUnum_sig) 	// output [7:0] OUnum_sig
);

